local_apps/frontend/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from local_apps.frontend import views as base_views

urlpatterns = [

	url(r'^$', base_views.home, name='Home'),
	url(r'^contacto/', base_views.contact, name='Contact'),
	url(r'^suscribirse/', base_views.susbcribe, name='Pray'),
	url(r'^quienes-somos/', base_views.about, name='About'),

	url(r'^multimedia/periodico/(?P<pk>[\w-]+)/', base_views.newspaper, name='Newspaper'),
	url(r'^multimedia/', base_views.media, name='Media'),

	url(r'^eventos/(?P<pk>[\w-]+)', base_views.events_detail, name='Event_detail'),
	url(r'^eventos/', base_views.events, name='Events'),

	url(r'^noticias/categoria/(?P<category>[\w-]+)/', base_views.blog_filter, name='Blog_category'),
	url(r'^noticias/(?P<slug>[\w-]+)/', base_views.blog_detail, name='Blog_details'),
	url(r'^noticias/', base_views.blog, name='Blog'),
	
	url(r'^proyectos/(?P<name>[\w-]+)/', base_views.projects_detail, name='Project_detail'),
	url(r'^proyectos/', base_views.projects, name='Projects'),

	url(r'^reuniones/(?P<pk>[\w-]+)/', base_views.reunions_detail, name='Reunions_detail'),
	url(r'^reuniones/', base_views.reunions, name='Reunions'),

	url(r'^testimonios/(?P<pk>[\w-]+)/', base_views.testimonials_detail, name='Testimonial_detail'),
	url(r'^testimonios/', base_views.testimonials, name='Testimonials'),
]

settings/urls.py
from django.conf import settings
from django.conf.urls import (include, url, handler400, handler403, handler404, handler500)
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers

from local_apps.profiles.auth import (login,register,logout,activate)
from local_apps.frontend import views as base_views

router = routers.DefaultRouter()
router.register(r'api/users', base_views.UserViewSet)
router.register(r'api/groups', base_views.GroupViewSet)
router.register(r'api/church', base_views.ChurchViewSet)

handler400 = 'local_apps.frontend.views.my_custom_bad_request_view'
handler403 = 'local_apps.frontend.views.my_custom_permission_denied_view'
handler404 = 'local_apps.frontend.views.my_custom_page_not_found_view'
handler500 = 'local_apps.frontend.views.my_custom_error_view'

urlpatterns = [

	url(r'^',include('local_apps.frontend.urls' ,namespace='frontend')),
	url(r'^auth/',include('local_apps.profiles.urls' ,namespace='auth')),
    url(r'^dashboard/',include('local_apps.dashboard.urls' ,namespace='dashboard')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

    url(r'^', include(router.urls)),
    url(r'^iurd/admin/', admin.site.urls),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

local_apps/medias/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator
from django.core.validators import URLValidator

from local_apps.iurd.models import Category,Project
from local_apps.news.models import Post
from ckeditor.fields import RichTextField


def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
	PostModel = instance.__class__
	model_name = instance.__class__.__name__

	# model_name =
	try:
		_id = PostModel.objects.order_by("id").last().id
	except Exception as e:
		_id = 0
	new_id = _id + 1
	"""
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
	# print(instance.__class__.__name__)
	return "%s/%s/%s" %(model_name,new_id,filename)


class Newspaper(models.Model):
	title = models.CharField(max_length=144)
	edition = models.PositiveIntegerField(validators=[MaxValueValidator(1000),])
	description = RichTextField()
	image = models.ImageField(upload_to=upload_location, 
	null=True, 
	blank=True, 
	width_field="width_field", 
	height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	newspaper_file = models.FileField(upload_to=upload_location,blank=True)
	newspaper_url = models.CharField(validators=[URLValidator()],max_length=144,blank=True)
	active = models.BooleanField(default=True)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ["-timestamp", "-updated"]
		verbose_name = ('Nuevo Periodico')
		verbose_name_plural = ('Periodicos')
		permissions = (
			("can_create_newspaper", "Puede crear periodicos"),
			("can_delete_newspaper", "Puede eliminar periodicos"),
			("can_update_newspaper", "Puede editar periodicos"),
		)

	def get_absolute_url(self):
		return reverse("frontend:Newspaper", kwargs={"id": self.id})


class Video(models.Model):
	title = models.CharField(max_length=144)
	description = RichTextField()
	image = models.ImageField(upload_to=upload_location, 
	null=True, 
	blank=True, 
	width_field="width_field", 
	height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	video_url = models.CharField(max_length=144,blank=True)
	video_file = models.FileField(upload_to=upload_location,blank=True)
	active = models.BooleanField(default=True)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	category = models.ForeignKey(Category, null=True, blank=True)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ["-timestamp", "-updated"]
		verbose_name = ('Nuevo video')
		verbose_name_plural = ('Videos')
		permissions = (
			("can_create_video", "Puede crear video"),
			("can_delete_video", "Puede eliminar video"),
			("can_update_video", "Puede editar video"),
		)


class Tv(models.Model):
	title = models.CharField(max_length=144)
	description = RichTextField()
	image = models.ImageField(
		upload_to=upload_location, 
		null=True, 
		blank=True, 
		width_field="width_field", 
		height_field="height_field"
	)
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	video_url = models.CharField(validators=[URLValidator()],max_length=144,blank=True)
	video_file = models.FileField(upload_to=upload_location,blank=True)
	active = models.BooleanField(default=True)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	category = models.ForeignKey(Category, null=True, blank=True)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ["-timestamp", "-updated"]
		verbose_name = ('Tv')
		verbose_name_plural = ('Tv')
		permissions = (
			("can_create_tv", "Puede crear tv"),
			("can_delete_tv", "Puede eliminar tv"),
			("can_update_tv", "Puede editar tv"),
		)


class Audio(models.Model):
	title = models.CharField(max_length=144)
	description = RichTextField()
	image = models.ImageField(
		upload_to=upload_location, 
		null=True, 
		blank=True, 
		width_field="width_field", 
		height_field="height_field"
	)
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	audio_url = models.CharField(
		validators=[URLValidator()],
		max_length=144,
		blank=True
	)
	audio_file = models.FileField(upload_to=upload_location,blank=True)
	active = models.BooleanField(default=True)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	category = models.ForeignKey(Category, null=True, blank=True)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ["-timestamp", "-updated"]
		verbose_name = ('Nuevo audio')
		verbose_name_plural = ('Audios')
		permissions = (
			("can_create_audio", "Puede crear audios"),
			("can_delete_audio", "Puede eliminar audios"),
			("can_update_audio", "Puede editar audios"),
		)


class Image(models.Model):
	title = models.CharField(max_length=144)
	description = RichTextField(blank=True)
	image = models.ImageField(
		upload_to=upload_location, 
		null=True, 
		blank=True, 
		width_field="width_field", 
		height_field="height_field"
	)
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	image_url = models.CharField(
		validators=[URLValidator()],
		max_length=144,
		blank=True
	)
	active = models.BooleanField(default=True)
	for_home = models.BooleanField(default=True)
	is_social = models.BooleanField(default=False)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	category = models.ForeignKey(Category, null=True, blank=True)
	project_related = models.ForeignKey(Project, related_name='image_project_related', blank=True, null=True)
	post_related = models.ForeignKey(Post, related_name='image_post_related', blank=True, null=True)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ["-timestamp", "-updated"]
		verbose_name = ('Nueva imagen')
		verbose_name_plural = ('Imagenes')
		permissions = (
			("can_create_image", "Puede crear imagenes"),
			("can_delete_image", "Puede eliminar imagenes"),
			("can_update_image", "Puede editar imagenes"),
		)
	



class Radio(models.Model):
	title = models.CharField(max_length=144)
	description = RichTextField()
	image = models.ImageField(
		upload_to=upload_location, 
		null=True, 
		blank=True, 
		width_field="width_field", 
		height_field="height_field"
	)
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	audio_url = models.CharField(validators=[URLValidator()],max_length=144,blank=True)
	audio_file = models.FileField(upload_to=upload_location,blank=True)
	active = models.BooleanField(default=True)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	category = models.ForeignKey(Category, null=True, blank=True)

	def __str__(self):
		return self.title

	class Meta:
		ordering = ["-timestamp", "-updated"]
		verbose_name = ('Radio')
		verbose_name_plural = ('Radio')
		permissions = (
			("can_create_radio", "Puede crear radio"),
			("can_delete_radio", "Puede eliminar radio"),
			("can_update_radio", "Puede editar radio"),
		)
		

local_apps/testimonials/models.py
from django.db import models
from django.core.validators import URLValidator
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.utils.text import slugify

from local_apps.iurd.models import Category
from ckeditor.fields import RichTextField

def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
	PostModel = instance.__class__
	model_name = instance.__class__.__name__
	# model_name =
	try:
		_id = PostModel.objects.order_by("id").last().id
	except Exception as e:
		_id = 0
	new_id = _id + 1
	"""
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
	# print(instance.__class__.__name__)
	return "%s/%s/%s" %(model_name,new_id, filename)

class Testimonial(models.Model):
	title = models.CharField(max_length=144)
	slug = models.SlugField(max_length=140, blank=True)
	publisher = models.CharField(max_length=144, default='User')
	description = RichTextField()
	image = models.ImageField(upload_to=upload_location, 
		null=True, 
		blank=True, 
		width_field="width_field", 
		height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	video_url = models.CharField(max_length=144,blank=True)
	video_file = models.FileField(upload_to=upload_location,blank=True)
	active = models.BooleanField(default=True)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	category = models.ForeignKey(Category, null=True, blank=True)

	def __str__(self):
		return self.slug

	def _get_unique_slug(self):
		slug = slugify(self.title)
		unique_slug = slug
		num = 1
		while Testimonial.objects.filter(slug=unique_slug).exists():
			unique_slug = '{}-{}'.format(slug, num)
			num += 1
		return unique_slug
 
	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = self._get_unique_slug()
		super().save()

	class Meta:
		ordering = ["-timestamp", "-updated"]
		verbose_name = ('Nuevo testimonio')
		verbose_name_plural = ('Testimonios')
		permissions = (
			("can_create_testimonial", "Puede crear testimonios"),
			("can_delete_testimonial", "Puede eliminar testimonios"),
			("can_update_testimonial", "Puede editar testimonios"),
	)

	def get_absolute_url(self):
		return reverse("frontend:Testimonial_detail", kwargs={"pk": self.slug})

templates/base/blog.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
    <meta property="og:url"           content="http://www.universal.org.pa/" />
    <meta property="og:type"          content="website" />
    <meta property="og:title"         content="{{title}} | {{site.name}}" />
    <meta property="og:description"   content="{{site.description}}" />
    <meta property="og:image"         content="{% static 'base/images/logo.png' %}" />
<style media="screen">
    .blog-post {background-color: #FFF;margin-bottom: 25px;}
    .blog-post .blog-post-pub-date {
        position: absolute;;
        height: 100px;
        width: 100px;
        background-color: #FFF;
        left: -90px;
    }
    .blog-post .blog-post-pub-date h4 {position: absolute;top:1px;left: 10px;}
    .blog-post .blog-post-pub-date h4 span {position: absolute;bottom: 0;left: 0px;top: 35px; font-family: 'Old Standard TT', serif;}
    .blog-post .blog-post-img {width: 100%;}
    .blog-post .blog-post-img h2 {width: 100%; background-color: rgba(64,69,69,0.5);color:#e9e5e5;position: relative;z-index: 3;margin-top: -50px;height: 50px;padding-top: 5px;padding-left: 15px; overflow: hidden;}
    .blog-post .blog-post-img h2 a{font-size: 18px !important;font-family: 'Old Standard TT', serif;color: #FFF}
    .blog-post .blog-post-img img{height: 100%; width: 100%}
    .blog-post .blog-post-img h2 a:hover,
    .blog-post .blog-post-img h2 a:active{text-decoration: none; cursor: pointer;}
    .blog-post .blog-post-content,.blog-post .blog-post-footer {padding: 15px;}
    .blog-post .blog-post-footer p {display: inline-block;}
    .blog-post .blog-post-footer p span .left {position: absolute;right: 0}
    .blog-post .blog-post-footer p span .right {position: absolute;left: 0}
    .blog-aside {background-color:#FFF;min-height:10px;margin-bottom: 25px;}
    .blog-aside-header {background-color: #FEFEFE; height: 70px;padding: 20px;}
    /*.blog-aside-header p {font-size: 1.35em;}*/
    .blog-aside-body {padding: 20px;}
    .blog-aside-body ul {padding: 0}
    .blog-aside-body ul li {list-style: none;}
    /*.blog-aside-body ul li a {font-size:1.31em;}*/
    .blog-aside-body ul li a span {font-size:0.671em;}
    .badge {background-color: #242843}
    .blog-aside-body ul li a:hover {text-decoration: none;}
    .blog-aside-search-input,.blog-aside-search-button {display: inline-block; height: 70px;}
    .blog-aside-search form {height: 70px;margin: 0;padding: 0;}
    .blog-aside-search-input,.blog-aside-search-button {display: inline-block;}
    .blog-aside-search-input {height: 95%;width: 80%; background-color: #fff;}
    .blog-aside-search-input input {border: none;margin: 0; padding: 15px 0 15px 10px;font-size: 1.3em;width: 100%;height: 105%}
    .blog-aside-search-button {height: 100%; width: 18.5%;margin: 0;padding: 0;position: absolute;}
    .blog-aside-search-button button {border: none;height: 70px;width: 100%;background-color: #5cc485}
    .glyphicon-search::before {font-size: 1.9em !important;}
    .blog-aside-fixed {position: fixed;width: 350px;}
    .blog-aside-fixed .blog-aside-search-button{width: 20%;}
    .modal-body img{width: 100%}
</style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="container">
            <div class="col-xs-12 col-sm-8">
                {% if news_list %}
                    {% for news in news_list %}
                        <div class="blog-post material-shadow">
                            <div class="blog-post-pub-date material-shadow hidden-xs hidden-sm hidden-md hidden-md hidden-lg">
                                <h4>{{news.timestamp|date:"D d M Y"}}</h4>
                            </div>
                            <div class="blog-post-img">
                                <img src="{% if news.image != '' %}{{news.image.url}}{% else %}https://static.pexels.com/photos/325288/pexels-photo-325288.jpeg{% endif %}" alt="">

                                <h2>
                                    <a href="{{news.get_absolute_url}}">{{news.title}}</a>
                                </h2>
                            </div>
                            <div class="blog-post-content">
                                {{news.content|safe|truncatewords_html:20}}
                            </div>
                            <div class="blog-post-footer">
                                <p>
                                    <span class="left glyphicon glyphicon-user"> {% if news.user.first_name %}{{news.user.first_name}}{% endif %} {% if news.user.last_name %}{{news.user.last_name}}{% endif %}</span>
                                </p>
                                <br>
                                {% if news.category %}
                                    <p>
                                        <a href="{{news.get_category_url}}">{{news.category}}</a>
                                    </p>
                                {% endif %}
                                <br>
                                {% if news.related %}<p><a href="">{{news.related.id}}</a></p>{% endif %}
                            </div>
                            <div  id="{{news.id}}Modal" class="modal" tabindex="-1" role="dialog">
                                <div class="modal-dialog modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-body">
                                           <img src="{% if news.image != '' %}{{news.image.url}}{% else %}https://static.pexels.com/photos/325288/pexels-photo-325288.jpeg{% endif %}" alt="">
                                           <h1>{{news.title}}</h1>
                                           {{news.content|safe}}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                <!-- Paginator -->
                <nav aria-label="...">
                    {% if news_list.has_other_pages %}
                    <ul class="pagination">
                        {% if news_list.has_previous %}
                        <li>
                            <a href="?page={{ news_list.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% else %}
                        <li class="disabled">
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        </li>
                        {% endif %}
                            {% for i in news_list.paginator.page_range %}
                                {% if news_list.number == i %}
                                    <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                                {% else %}
                                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                                {% endif %}
                            {% endfor %}
                        {% if news_list.has_next %}
                        <li>
                            <a href="?page={{ news_list.next_page_number }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                        </li>
                        {% else %}
                            <li class="disabled"><span>&raquo;</span></li>
                        {% endif %}
                    </ul>
                    {% endif %}
                </nav>

            </div>
            <div class="col-sm-4 hidden-xs">
                {% if site_categories %}
                    <div class="blog-aside material-shadow" id="blogCategoriesAside">
                        <div class="blog-aside-header">
                            <p>Categorías</p>
                        </div>
                        <div class="blog-aside-body">
                            <ul class="" id="">
                                    {% for category in site_categories %}
                                    <li class="" id="">
                                        <a href="{% url 'frontend:Blog_category' category.id %}" class="" id="">
                                            {{category.name}}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
<script type="text/javascript">

$(function(){
    var menu = $("#blogSeachAside");
    $(window).scroll(function(){
        var scroll = $(window).scrollTop();
        if (scroll >= 1080){
            if(!menu.hasClass("blog-aside-fixed")){
                menu.addClass('blog-aside-fixed').fadeIn(1000);
            }
        } else {
            if(menu.hasClass("blog-aside-fixed")){
                menu.removeClass("blog-aside-fixed").fadeIn(1000);
            }
        }
    });
})
</script>
{% endblock %}

templates/base/events.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
<style media="screen">
    .box{padding:15px; background-color: #EfEfEf; }
</style>
{% endblock %}
{% block content %}

{% if page_events %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 text-center">
            <h4>Proximos eventos</h4>
        </div>
        {% for event in events %}
            <div class="col-xs-12 col-sm-4">
                <div class="card-3 box">
                    <h3 class="text-center"><a href="{{event.get_absolute_url}}">{{event.title}}</a></h3>
                    {{event.description|safe|truncatewords_html:20}}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endif %}

{% endblock %}

{% block js %}
<script>

</script>
{% endblock %}

templates/base/media.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
<style>
	.testimonial-post-header img {height: 100%; width: 100%}
</style>
{% endblock %}

{% block content %}
{% if newspaper %}
    <div class="row">
        <div class="container">
            {% for newspapper in newspaper_list %}
                <div class="col-xs-12 col-sm-4">
                    <div class="panel panel-default">
                        <div class="panel-heading"><h3>{{newspapper.title}}</h3></div>
                        <div class="panel-body">{{newspapper.description|safe}}</div>
                        <div class="panel-footer">
                            <a class="" href="{% if newspapper.newspapper_file %}{{newspapper.newspapper_file}}{% endif %}"><img src="{% static 'base/images/pdf-icon.png' %}" width="55" alt="{{newspapper.title}}"></a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

<div class="row testimonios">
    {% if video_list %}
        <div class="container">
            {% for video in video_list %}
                <div class="col-xs-12 col-sm-4 testimonial-block">
                    <div class="testimonial-post material-shadow">
                        <div class="testimonial-post-header">
                            <a data-toggle="modal" data-target="#{{video.id}}Modal">
                                <img id="" src="{% if video.image != '' %}{{video.image.url}}{% else %}https://static.pexels.com/photos/325288/pexels-photo-325288.jpeg{% endif %}" alt="">
                            </a>
                            <h3>{{video.title}}</h3>
                        </div>
                        <div class="testimonial-post-footer text-right">
                            <p>
                                <span class="">
                                    Publicado {{video.timestamp|date:"D d M Y"}}
                                </span>
                            </p>
                        </div>
                    </div>
                </div>
                <div  id="{{video.id}}Modal" class="modal" tabindex="-1" role="dialog">
                    <div class="modal-dialog modal-lg" role="document">
                        <div class="modal-content">
                            <div class="modal-body">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><h5>&times;</h5></span></button>
                                <iframe src="https://www.youtube.com/embed/{{video.video_url}}" frameborder="0"></iframe>
                            </div>
                        </div>
                    </div>
                </div>        
            {% endfor %}
        </div>
    {% endif %}
</div>
{% endblock %}

{% block js %}
{% endblock %}

templates/base/project.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
<style media="screen">
    .project {height: 320px;}
    .group-container{margin-bottom: 15px; background-color: #665656;background-color: #FFF;overflow: hidden; width: 100%;padding:10px 20px; }
    .group-container a{background-color: rgba(64,64,64,.3);}
    .group-container a:hover{text-decoration: none;}
    /*.group-image{height: 350px;}*/
    .group-image img{max-height: 250px; max-width: 250px;}

</style>
{% endblock %}

{% block content %}
<!-- Projects -->
<div class="container">
    <!-- Our projects -->
        <div class="row">
            <div class="groups-container">
                {% if groups %}
                    <div class="col-xs-12 {% if not eventa %} col-sm-offset-2 {% endif %} col-sm-8">
                        {% for group in groups %}
                            <div class="group-container card-3">
                                <div class="col-xs-12 col-sm-8">
                                    <div class="group-content">
                                        <h3>{{group.title}}</h3>
                                        {{group.description|safe|truncatewords_html:20}}
                                        <p><a class="btn btn-link" href="{{group.get_absolute_url}}">Ver más</a></p>
                                    </div>
                                </div>
                                <div class="col-xs-12 col-sm-4">
                                    <div class="group-image text-center">
                                        <img src="{% if group.image.url %}{{group.image.url}}{% else %}{% endif %}" alt="" style="background-size: 300px;background-repeat: no-repeat">
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                {% if events %}
                    <div class="col-xs-12 col-sm-4">
                        <div class="banner-home card-3">
                            <a href="{{event.get_absolute_url}}">
                                <img src="{% if event.banner_vertical %}{{event.banner_vertical.url}}{% else %}{{event.image.url}}{% endif %}" alt="{{event.title}}">
                            </a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    <!-- Our Projects -->
</div>
{% endblock %}

{% block js %}
<script>
    
</script>
{% endblock %}