local_apps/frontend/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from local_apps.frontend import views as base_views

urlpatterns = [

	url(r'^$', base_views.home, name='Home'),
	url(r'^contacto/', base_views.contact, name='Contact'),
	url(r'^suscribirse/', base_views.susbcribe, name='Pray'),
	url(r'^quienes-somos/', base_views.about, name='About'),

	url(r'^multimedia/periodico/(?P<pk>[\w-]+)/', base_views.newspaper, name='Newspaper'),
	url(r'^multimedia/', base_views.media, name='Media'),

	url(r'^eventos/(?P<pk>[\w-]+)', base_views.events_detail, name='Event_detail'),
	url(r'^eventos/', base_views.events, name='Events'),

	url(r'^noticias/categoria/(?P<category>[\w-]+)/', base_views.blog_filter, name='Blog_category'),
	url(r'^noticias/(?P<slug>[\w-]+)/', base_views.blog_detail, name='Blog_details'),
	url(r'^noticias/', base_views.blog, name='Blog'),
	
	url(r'^proyectos/(?P<name>[\w-]+)/', base_views.projects_detail, name='Project_detail'),
	url(r'^proyectos/', base_views.projects, name='Projects'),

	url(r'^reuniones/(?P<pk>[\w-]+)/', base_views.reunions_detail, name='Reunions_detail'),
	url(r'^reuniones/', base_views.reunions, name='Reunions'),

	url(r'^testimonios/(?P<pk>[\w-]+)/', base_views.testimonials_detail, name='Testimonial_detail'),
	url(r'^testimonios/', base_views.testimonials, name='Testimonials'),
]

local_apps/profiles/urls.py
from django.conf.urls import url
from django.contrib import admin

from local_apps.profiles.auth import (login, logout, register, activate)

urlpatterns = [
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', activate, name='Activate'),
    url(r'^entrar/', login , name='Login'),
    url(r'^registro/', register , name='Register'),
    url(r'^salir/', logout , name='Logout'),
]

settings/urls.py
from django.conf import settings
from django.conf.urls import (include, url, handler400, handler403, handler404, handler500)
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers

from local_apps.profiles.auth import (login,register,logout,activate)
from local_apps.frontend import views as base_views

router = routers.DefaultRouter()
router.register(r'api/users', base_views.UserViewSet)
router.register(r'api/groups', base_views.GroupViewSet)
router.register(r'api/church', base_views.ChurchViewSet)

handler400 = 'local_apps.frontend.views.my_custom_bad_request_view'
handler403 = 'local_apps.frontend.views.my_custom_permission_denied_view'
handler404 = 'local_apps.frontend.views.my_custom_page_not_found_view'
handler500 = 'local_apps.frontend.views.my_custom_error_view'

urlpatterns = [

	url(r'^',include('local_apps.frontend.urls' ,namespace='frontend')),
	url(r'^auth/',include('local_apps.profiles.urls' ,namespace='auth')),
    url(r'^dashboard/',include('local_apps.dashboard.urls' ,namespace='dashboard')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

    url(r'^', include(router.urls)),
    url(r'^iurd/admin/', admin.site.urls),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

local_apps/testimonials/models.py
from django.db import models
from django.core.validators import URLValidator
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.utils.text import slugify

from local_apps.iurd.models import Category
from ckeditor.fields import RichTextField

def upload_location(instance, filename):
    #filebase, extension = filename.split(".")
    #return "%s/%s.%s" %(instance.id, instance.id, extension)
	PostModel = instance.__class__
	model_name = instance.__class__.__name__
	# model_name =
	try:
		_id = PostModel.objects.order_by("id").last().id
	except Exception as e:
		_id = 0
	new_id = _id + 1
	"""
    instance.__class__ gets the model Post. We must use this method because the model is defined below.
    Then create a queryset ordered by the "id"s of each object, 
    Then we get the last object in the queryset with `.last()`
    Which will give us the most recently created Model instance
    We add 1 to it, so we get what should be the same id as the the post we are creating.
    """
	# print(instance.__class__.__name__)
	return "%s/%s/%s" %(model_name,new_id, filename)

class Testimonial(models.Model):
	title = models.CharField(max_length=144)
	slug = models.SlugField(max_length=140, blank=True)
	publisher = models.CharField(max_length=144, default='User')
	description = RichTextField()
	image = models.ImageField(upload_to=upload_location, 
		null=True, 
		blank=True, 
		width_field="width_field", 
		height_field="height_field")
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	video_url = models.CharField(max_length=144,blank=True)
	video_file = models.FileField(upload_to=upload_location,blank=True)
	active = models.BooleanField(default=True)
	publish = models.DateField(auto_now=False, auto_now_add=False)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	category = models.ForeignKey(Category, null=True, blank=True)

	def __str__(self):
		return self.slug

	def _get_unique_slug(self):
		slug = slugify(self.title)
		unique_slug = slug
		num = 1
		while Testimonial.objects.filter(slug=unique_slug).exists():
			unique_slug = '{}-{}'.format(slug, num)
			num += 1
		return unique_slug
 
	def save(self, *args, **kwargs):
		if not self.slug:
			self.slug = self._get_unique_slug()
		super().save()

	class Meta:
		ordering = ["-timestamp", "-updated"]
		verbose_name = ('Nuevo testimonio')
		verbose_name_plural = ('Testimonios')
		permissions = (
			("can_create_testimonial", "Puede crear testimonios"),
			("can_delete_testimonial", "Puede eliminar testimonios"),
			("can_update_testimonial", "Puede editar testimonios"),
	)

	def get_absolute_url(self):
		return reverse("frontend:Testimonial_detail", kwargs={"pk": self.slug})

templates/detail/blogs.html
{% extends 'base.html' %}
{% block css %}
<style>
	.go-back{margin-top: 25px;}
	#fullWidthImage1 {
        height: 50vh;
        background-image: url("{{blog_detail.image.url}}");
    }
	.quote-image {
        -webkit-background-size: cover !important;
        -moz-background-size: cover !important;
        -o-background-size: cover !important;
        background-size: contain !important;
        background-repeat: no-repeat !important;
        background-position: center !important;
        background-attachment: inherit !important;
        position: relative !important;
    }
    .quote-image::before {
        opacity: 0.099;
    }
    .quote-image .container h4 {position: relative;max-width: 35vw;margin:10% auto;text-align: center;font-size: 2.8em;}
    .post,.comments{padding: 25px;background-color: #FFF; margin-top: 25px; }
    .comment{border-top: 1px solid #CCC; padding-top:10px; }
    .comment .comment-author{width: 60px; background-color: #e4e4e4; height: auto}
	.navbar {margin-bottom: 0px;}
	.banner-home{height: auto !important; margin-bottom: 25px;}
	.banner-home img{height: 100% !important;}
</style>
<meta property="og:url"           content="http://www.universal.org.pa{{blog_detail.get_absolute_url}}" />
<meta property="og:type"          content="website" />
<meta property="og:title"         content="{{blog_detail.title}}" />
<meta property="og:description"   content="{{blog_detail.content }}" />
<meta property="og:image"         content="http://www.universal.org.pa/{{blog_detail.image.url}}" />
{% endblock %}

{% block content %}

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-offset-2 col-sm-8">
			<div class="go-back">
				<p>
					<a href="{% url 'frontend:Blog' %}">
						<span class="glyphicon glyphicon-menu-left">
						</span>
						Ver todos los artículos
					</a>
				</p>
			</div>
		</div>
		<div class="col-xs-12 col-sm-offset-2 col-sm-8">
			<div class="post card-3">
				<div class=" hidden-xs imge-parallax">
                    <div id="fullWidthImage1" class="quote-image">
                    </div>
                </div>
				<div class="post-author">
					
				</div>
				<div class="post-content">
					<br>
					<h4>{{blog_detail.title}}</h4>
					<hr>
					{{blog_detail.content | safe}}
					<hr>
				</div>
				<div id="fb-root"></div>
				<script>
					(function(d, s, id) {
						var js, fjs = d.getElementsByTagName(s)[0];
						if (d.getElementById(id)) return;
						js = d.createElement(s); js.id = id;
						js.src = "//connect.facebook.net/es_LA/sdk.js#xfbml=1";
						fjs.parentNode.insertBefore(js, fjs);
					}(document, 'script', 'facebook-jssdk'));

				</script>
				<div class="fb-like" data-href="http://www.universal.org.pa{{blog_detail.get_absolute_url}}" data-layout="button_count" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
				<a 
				href="whatsapp://send" 
				data-text="Compartir {{blog_detail.title}}" 
				data-href="whatsapp://send" 
				class="hidden-sm hidden-md hidden-lg">
					Compartir en whatsapp
				</a>
			</div>
		</div>
		<div class="col-sm-4">
			{% if blog_detail.related.all %}
				<div class="related">
					<h3>Artículos relacionados</h3>
					<ul>
						{% for related in blog_detail.related.all %}
							<li>
								<a href="{{related.get_absolute_url}}">
									{{related}}
								</a>
							</li>
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			{% if events %}
                <div class="banner-home card-3">
                    <a href="{{event.get_absolute_url}}">
                        <img src="{% if event.banner_vertical %}{{event.banner_vertical.url}}{% else %}{{event.image.url}}{% endif %}" alt="{{event.title}}">
                    </a>
	            </div>
	        {% endif %}
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-offset-2 col-md-8">
			
			<div class="comments card-3">
				<div class="header text-center">
					<h4>Ultimos comentarios</h4>
				</div>
				<div class="fb-comments" data-href="http://www.universal.org.pa{{blog_detail.get_absolute_url}}" data-numposts="10"></div>
				{% if comments %}
					{% for comment in comments %}
						<div class="comment">
							<div class="comment-author">
								
							</div>
							<div class="content">
								{{comment.content|safe}}
							</div>
						</div>
					{% endfor %}
					{% else %}
						<!-- <div class="comment">
							<p>Aún no hay comentario</p>
						</div> -->
				{% endif %}
			</div>
			{% if user.is_anonymous %}
				<div class="comments card-3">
					<div class="header text-center">
						<h4>Iniciar sesión</h4>
					</div>
					<form method="post" action="{% url 'auth:Login' %}">
						{% csrf_token %}
						<input type="text" class="form-control" id="lg_username" name="username" placeholder="Escriba su correo eléctronico">

						<input type="password" class="form-control" id="lg_password" name="password" placeholder="Escriba su contraseña">

						<button type="submit" class="btn btn-block btn-primary">
							Entrar
						</button>
					</form>		
				</div>
			{% else %}
				<div class="comments card-3">
					<div class="header text-center">
						<h4>Escribe un comentario</h4>
					</div>
					<form method="post" action="{# url 'frontend:comment' #}">
						{% csrf_token %}
						<input type="text" class="form-control" id="lg_username" name="username" placeholder="Escriba su correo eléctronico">

						<input type="text" class="hidden" value="{{blog_detail.content_type}}" name="content_type">

						<input type="text" class="hidden" value="{{blog_detail.object_id}}" name="object_id">

						<input type="text" class="hidden" value="" name="">

						<textarea class="form-control" rows="3" class="form-control" placeholder="Escriba su comentario" name="content">
						</textarea>
						<button type="submit" class="btn btn-block btn-primary">
							Entrar
						</button>
					</form>		
				</div>
			{% endif %}

		</div>
	</div>
</div>


{% endblock %}

{% block js %}

{% endblock %}

templates/detail/events.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
<style>
    .go-back{margin-top: 25px;}
    #fullWidthImage1 {
        height: 50vh;
        background-image: url("{% if object.image.url %}{{object.image.url}}{% else %}{% endif %}");
    }
    .imge-parallax{
        margin-top:-27px;
    }
    .quote-image::before {
        opacity: 0.799;
    }
    .quote-image .container h4 {position: relative;max-width: 35vw;margin:10% auto;text-align: center;font-size: 2.8em;}
    .box{padding: 25px;background-color: #EfEfEf; margin-top: 25px; }
    .navbar {margin-bottom: 0px;}
    .banner-home{height: auto !important; margin-bottom: 25px;}
    .banner-home img{height: 100% !important;}
</style>
{% endblock %}

{% block content %}
<div class="row hidden-xs vh50 imge-parallax">
    <div id="fullWidthImage1" class="quote-image">
        <div class="container">
            <h4>{{object.title}}</h4>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="go-back">
                <p><a href="{% url 'frontend:Events' %}"><span class="glyphicon glyphicon-menu-left"></span> Ver todos los eventos</a></p>
            </div>
        </div>
        <div class="col-xs-12 col-sm-offset-2 col-sm-8">
            <div class="card-3 box">
                <h2>{{object.title}}</h2>
                {{object.description| safe}}
                {{object.location| safe}}
            </div>
        </div>
        <div class="hidden-xs col-sm-4">
            {% if articles %}
            <h4>Articulos relacionados</h4>
                {% for article in articles %}
                    <div class="card-3 box">
                        <div class="article-image">
                            <img src="" alt="">
                        </div>
                        <p><a href="{{article.get_absolute_url}}">{{article.title}}</a></p>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

{% block js %}
{% endblock %}

templates/detail/projects.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
<style>
    .go-back{margin-top: 25px;}
    #fullWidthImage1 {
        height: 50vh;
        background-image: url("{% if project.background_image.url %}{{project.background_image.url}}{% else %}{% endif %}");
    }
    .quote-image {
        -webkit-background-size: cover !important;
        -moz-background-size: cover !important;
        -o-background-size: cover !important;
        background-size: contain !important;
        background-repeat: no-repeat !important;
        background-position: center !important;
        background-attachment: inherit !important;
        position: relative !important;
    }
    .quote-image::before {
        opacity: 0.2799;
    }
    .quote-image .container h4 {position: relative;max-width: 35vw;margin:10% auto;text-align: center;font-size: 2.8em;}
    .box{padding: 25px;background-color: #FFF; margin-top: 25px; }

    .navbar {margin-bottom: 0px;}
    .banner-home{height: auto !important; margin-bottom: 25px;}
    .banner-home img{height: 100% !important;}
    .blog-lg .swiper-container {
        width: 100%;
        height: 180px;
        margin: 20px auto;
    }
    .blog-lg .swiper-slide {
        text-align: center;
        font-size: 18px;
        background: #fff;
        height: 160px; width: 160px;
        
        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
    }
    .blog-lg .swiper-slide img{
        min-width:100%;
        max-width:100%;
        min-height:100%;
        max-height:100%;
    }
    .blog-lg .swiper-slide p{
        position: absolute;top: 100%;    top: 80%;
        background: rgba(255,255,255,1);
        width: 100%;
        padding: 5px;
    }
</style>
{% endblock %}

{% block content %}


<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-offset-1 col-sm-10">
            <div class="go-back">
                <p><a href="{% url 'frontend:Projects' %}"><span class="glyphicon glyphicon-menu-left"></span> Ver todos los grupos</a></p>
            </div>
        </div>
        <div class="col-xs-12 col-sm-offset-1 col-sm-10">
            <div class="card-3 box">
                <div class=" hidden-xs imge-parallax">
                    <div id="fullWidthImage1" class="quote-image">
                    </div>
                </div>
                <h2>{{project.title}}</h2>
                {{project.description| safe}}
                <p><a href="{{project.url}}">Sitio oficial</a></p>
                <p>
                    {{project.category}}
                </p>
            </div>
        </div>
        {% if events %}
            <div class="col-xs-12 col-sm-4">
                <div class="banner-home card-3">
                    <a href="{{event.get_absolute_url}}">
                        <img src="{% if event.banner_vertical %}{{event.banner_vertical.url}}{% else %}{{event.image.url}}{% endif %}" alt="{{event.title}}">
                    </a>
                </div>
            </div>
        {% endif %}
    </div>
</div>


{% if has_news %}
    <br><br>
    <div class="row gray margin-top-25 margin-bottom-25">
        <div class="hidden-xs hidden-sm container">
            <div class="col-xs-12 blog-lg">
                <div class="swiper-container">
                    <div class="swiper-wrapper">
                        {% for new in news %}
                            <div class="swiper-slide">
                                <img src="{% if new.image %}{{new.image.url}}{% endif %}" alt="" class="img-responsive">
                                <p>
                                    <a href="{{new.url_new}}" target="_blank">{{new.title}}</a>
                                </p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}

<!-- Carrusel trabajo social -->
    {% if imagens %}
        <br><br>
        <div class="row">
            <div class="container">
                <div class="col-xs-12 col-sm-10 col-sm-offset-1">
                        <div class="social-carousel card-3">    
                            <div class="swiper-container">
                                <div class="swiper-wrapper">
                                    {% for imagen in imagens %}
                                        <div class="swiper-slide">
                                            <a>
                                                <img src="{{imagen.image.url}}" alt="{{imagen.title}}">
                                            </a>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <!-- Add Pagination -->
                            <div class="swiper-pagination"></div>
                            <!-- Add Arrows -->
                            <div class="swiper-button-next"></div>
                            <div class="swiper-button-prev"></div>
                        </div>
                    </div>
            </div>
        </div>
    {% endif %}   
<!-- Carrusel trabajo social -->

{% endblock %}

{% block js %}
<script>
    var swiper;
    swiper = new Swiper(
        '.blog-lg .swiper-container', {
            pagination: '.blog-lg .swiper-pagination',
            slidesPerView: 'auto',
            paginationClickable: true,
            spaceBetween: 30,
            freeMode: true
        }
    );
    
    swipper = new Swiper(
        '.social-carousel .swiper-container', {
            pagination: '.social-carousel .swiper-pagination',
            nextButton: '.social-carousel .swiper-button-next',
            prevButton: '.social-carousel .swiper-button-prev',
            paginationClickable: true
        }
    );
</script>
{% endblock %}

templates/detail/reunions.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
<style>
    .go-back{margin-top: 25px;}
    #fullWidthImage1 {
        height: 30vh;
        background-image: url("{% if object.background_image %}{{object.background_image.url}}{% else %}{% endif %}");
    }
    .imge-parallax{
        margin-top:-27px;
    }
    .quote-image {
        -webkit-background-size: cover !important;
        -moz-background-size: cover !important;
        -o-background-size: cover !important;
        background-size: contain !important;
        background-repeat: no-repeat !important;
        background-position: center !important;
        background-attachment: inherit !important;
        position: relative !important;
    }
    .quote-image::before {
        opacity: 0.0399;
    }
    .quote-image .container h4 {position: relative;max-width: 35vw;margin:10% auto;text-align: center;font-size: 2.8em;}
    .box{padding: 25px;background-color: #FFF; margin-top: 25px; }
    .video iframe{width: 100%; height: 450px;}
    .navbar {margin-bottom: 0px;}
    .banner-home{height: auto !important; margin-bottom: 25px;}
    .banner-home img{height: 100% !important;}
    .blog-lg .swiper-container {
        width: 100%;
        height: 180px;
        margin: 20px auto;
    }
    .blog-lg .swiper-slide {
        text-align: center;
        font-size: 18px;
        background: #fff;
        height: 160px; width: 160px;
        
        /* Center slide text vertically */
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
    }
    .blog-lg .swiper-slide img{
        min-width:100%;
        max-width:100%;
        min-height:100%;
        max-height:100%;
    }
    .blog-lg .swiper-slide p{
        position: absolute;top: 100%;    top: 80%;
        background: rgba(255,255,255,1);
        width: 100%;
        padding: 5px;
    }
</style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-offset-2 col-sm-8">
                <div class="go-back">
                    <p><a href="{% url 'frontend:Reunions' %}"><span class="glyphicon glyphicon-menu-left"></span> Ver todas las reuniones</a></p>
                </div>
            </div>
            <div class="col-xs-12 {% if not events %} col-sm-offset-2 {% endif %} col-sm-8">
                <div class="card-3 box">
                    <div id="fullWidthImage1" class="quote-image">
                        <div class="container">
                        </div>
                    </div>
                    <h2>{{object.title}}</h2>
                    {{object.description| safe}}
                    {{object.location| safe}}

                </div>
            </div>
            {% if events %}
                <div class="col-xs-12 col-sm-4">
                    <div class="banner-home card-3">
                        <a href="{{event.get_absolute_url}}">
                            <img src="{% if event.banner_vertical %}{{event.banner_vertical.url}}{% else %}{{event.image.url}}{% endif %}" alt="{{event.title}}">
                        </a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>

    {% if has_news %}
        <br><br>
        <div class="row gray margin-top-25 margin-bottom-25">
            <div class="container">
                <div class="col-xs-12 blog-lg">
                    <div class="swiper-container">
                        <div class="swiper-wrapper">
                            {% for new in news %}
                                <div class="swiper-slide">
                                    <img src="{% if new.image %}{{new.image.url}}{% endif %}" alt="" class="img-responsive">
                                    <p>
                                        <a href="{{new.get_absolute_url}}" target="_blank">{{new.title}}</a>
                                    </p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Add Arrows -->
                    <div class="swiper-button-next "></div>
                    <div class="swiper-button-prev "></div>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}

{% block js %}
<script>
    var swiper;
    swiper = new Swiper(
        '.blog-lg .swiper-container', {
            pagination: '.blog-lg .swiper-pagination',
            nextButton: '.blog-lg .swiper-button-next',
            prevButton: '.blog-lg .swiper-button-prev',
            slidesPerView: 'auto',
            paginationClickable: true,
            spaceBetween: 30,
            freeMode: true
        }
    );
</script>
{% endblock %}

templates/detail/testimonials.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
<style>
    .go-back{margin-top: 25px;}
    #fullWidthImage1 {
        height: 50vh;
        background-image: url("{% if object.image %}{{object.image.url}}{% else %}{% endif %}");
    }
    .imge-parallax{
        margin-top:-27px;
    }
    .quote-image::before {
        opacity: 0.799;
    }
    .quote-image .container h4 {position: relative;max-width: 35vw;margin:10% auto;text-align: center;font-size: 2.8em;}
    .box{padding: 25px;background-color: #FFF; margin-top: 25px; overflow: hidden; }
    .video iframe{width: 100%; height: 450px;}
    @media (max-width: 1024px) {
        .video iframe{width: auto; height: auto;}
    }
    .banner-home{height: auto !important; margin-bottom: 25px;}
    .banner-home img{height: 100% !important;}
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="go-back">
                <p><a href="{% url 'frontend:Testimonials' %}"><span class="glyphicon glyphicon-menu-left"></span> Ver todos los testimonios</a></p>
            </div>
        </div>
        <div class="col-xs-12 col-sm-offset-2 col-sm-8">
            <div class="card-3 box">
                <div class="col-xs-12">
                    <h2>
                        {{object.title}}
                    </h2>
                    <div>
                        {{object.description| safe}}
                        {{object.location| safe}}
                    </div>
                </div>
                {% if object.video_url %}
                    <div class="col-xs-12">
                        <div class="video">
                            <iframe src="https://www.youtube.com/embed/{{object.video_url}}" frameborder="0"></iframe>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
        {% if events %}
            <div class="col-xs-12 col-sm-4">
                <div class="banner-home card-3">
                    <a href="{{event.get_absolute_url}}">
                        <img src="{% if event.banner_vertical %}{{event.banner_vertical.url}}{% else %}{{event.image.url}}{% endif %}" alt="{{event.title}}">
                    </a>
                </div>
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block js %}
{% endblock %}