local_apps/frontend/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from local_apps.frontend import views as base_views

urlpatterns = [

	url(r'^$', base_views.home, name='Home'),
	url(r'^contacto/', base_views.contact, name='Contact'),
	url(r'^suscribirse/', base_views.susbcribe, name='Pray'),
	url(r'^quienes-somos/', base_views.about, name='About'),

	url(r'^multimedia/periodico/(?P<pk>[\w-]+)/', base_views.newspaper, name='Newspaper'),
	url(r'^multimedia/', base_views.media, name='Media'),

	url(r'^eventos/(?P<pk>[\w-]+)', base_views.events_detail, name='Event_detail'),
	url(r'^eventos/', base_views.events, name='Events'),

	url(r'^noticias/categoria/(?P<category>[\w-]+)/', base_views.blog_filter, name='Blog_category'),
	url(r'^noticias/(?P<slug>[\w-]+)/', base_views.blog_detail, name='Blog_details'),
	url(r'^noticias/', base_views.blog, name='Blog'),
	
	url(r'^proyectos/(?P<name>[\w-]+)/', base_views.projects_detail, name='Project_detail'),
	url(r'^proyectos/', base_views.projects, name='Projects'),

	url(r'^reuniones/(?P<pk>[\w-]+)/', base_views.reunions_detail, name='Reunions_detail'),
	url(r'^reuniones/', base_views.reunions, name='Reunions'),

	url(r'^testimonios/(?P<pk>[\w-]+)/', base_views.testimonials_detail, name='Testimonial_detail'),
	url(r'^testimonios/', base_views.testimonials, name='Testimonials'),
]

settings/urls.py
from django.conf import settings
from django.conf.urls import (include, url, handler400, handler403, handler404, handler500)
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers

from local_apps.profiles.auth import (login,register,logout,activate)
from local_apps.frontend import views as base_views

router = routers.DefaultRouter()
router.register(r'api/users', base_views.UserViewSet)
router.register(r'api/groups', base_views.GroupViewSet)
router.register(r'api/church', base_views.ChurchViewSet)

handler400 = 'local_apps.frontend.views.my_custom_bad_request_view'
handler403 = 'local_apps.frontend.views.my_custom_permission_denied_view'
handler404 = 'local_apps.frontend.views.my_custom_page_not_found_view'
handler500 = 'local_apps.frontend.views.my_custom_error_view'

urlpatterns = [

	url(r'^',include('local_apps.frontend.urls' ,namespace='frontend')),
	url(r'^auth/',include('local_apps.profiles.urls' ,namespace='auth')),
    url(r'^dashboard/',include('local_apps.dashboard.urls' ,namespace='dashboard')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

    url(r'^', include(router.urls)),
    url(r'^iurd/admin/', admin.site.urls),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="es-co">
<head>
    {% if redirect %}
        <script>
            window.location('http://universal.org.mx')
        </script>
    {% endif %}
    <meta charset="UTF-8">
    <link rel="alternate" href="https://www.universal.org.pa" hreflang="en-us" />
    <link rel="dns-prefetch" href="http://45.55.120.144:8686/">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="google-site-verification" content="nqBuxj97RxTr3zitI03pNYpdu77orz7vO3xruIo_tvk" />
    <meta name="robots" content="index, follow">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    {% if site %}
        <title>{{title}} | {{site.name}}</title>
        <meta name="description" content="{{site.description}}">
        <meta name="keywords" content="{{site.keywords}}">
        <meta name="author" content="{{site.author}}">
        {% if pg_title != 'blog' %}
            <meta property="og:url"           content="http://www.universal.org.pa/" />
            <meta property="og:type"          content="website" />
            <meta property="og:title"         content="{{title}} | {{site.name}}" />
            <meta property="og:description"   content="{{site.description}}" />
            <meta property="og:image"         content="{% static 'base/images/logo.png' %}" />
        {% endif %}
    {% else %}
        <title>{{title}} | Iglesia Universal Del Reino de Dios</title>
    {% endif %}
    <style>.async-hide { opacity: 0 !important} </style>
    <script>(function(a,s,y,n,c,h,i,d,e){s.className+=' '+y;h.start=1*new Date;
    h.end=i=function(){s.className=s.className.replace(RegExp(' ?'+y),'')};
    (a[n]=a[n]||[]).hide=h;setTimeout(function(){i();h.end=null},c);h.timeout=c;
    })(window,document.documentElement,'async-hide','dataLayer',4000,
    {'GTM-5LPFSMM':true});</script>
    {% include 'head.html' %}
    {% block css %}{% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-WTVZH7M" height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    {% include 'header.html' %}
    <section>{% block content %}{% endblock %}</section>
    <footer>
        {% include 'footer.html' %}
    </footer>
    <script src="{% static 'base/js/bootstrap.min.js' %}" charset="utf-8"></script>
    <script src="{% static 'base/js/app.js' %}" charset="utf-8"></script>
    <script src="{% static 'base/js/swiper.min.js' %}" charset="utf-8"></script>
    {% block js %}{% endblock %}
</body>
</html>

templates/footer.html
<div id="footerRow1" class="row footer-row ident-color">{% load staticfiles %}
    <div class="container hidden-xs">
        <div class="col-xs-12 col-md-3 hidden-sm">
            <div class="img-logo-footer">
                <img src="{% static 'base/images/isotipo.png' %}" alt="Iglesia oración fuerte al Espiritu Santo" class="img-responsive">
            </div>
        </div>
        {% if page_news %}
        <div class="col-xs-12 col-sm-4 col-md-3">
            <ul id="footerCol1Row" class="footer-list">
                <li class="" id="">Últimos artículos</li>
                {% for new in page_news %}<li class="footer-anchor" id=""><a href="{{new.get_absolute_url}}" >{{new.title}}</a></li>{% endfor %}
            </ul>
        </div>
        {%endif%}
        {% if feeds %}
        <div class="col-xs-12 col-sm-4 col-md-3">
            <ul id="footerCol2Row" class="footer-list">
                <li class="" id="">Blogs amigos</li>
                {% for feed in feeds %}<li class="footer-anchor" id=""><a href="{{feed.url_feed}}" target="_blank">{{feed.title}}</a></li>{% endfor %}
            </ul>
        </div>
        {%endif%}
        <div class="col-xs-12 col-sm-4 col-md-3">
            <ul id="footerCol4Row" class="footer-list">
                <li class="text-center" id="">Redes sociales</li>
            </ul>
            <br>
            <div class="text-center">
                <a href="{% url 'social:begin' 'facebook' %}" type="button" class="btn footer-sm-facebook btn-circle btn-lg" target="_blank">
                    <i class="fa fa-facebook footer-sm text-white" aria-hidden="true"></i>
                </a>
                <a type="button" class="btn footer-sm-youtube btn-circle btn-lg" href="https://www.youtube.com/channel/UCxDrDoFOgKPbgSwq_A4ptAQ">
                    <i class="fa fa-youtube footer-sm text-white" aria-hidden="true"></i>
                </a>
                <a type="button" class="btn footer-sm-facebook btn-circle btn-lg" href="https://www.instagram.com/iurdpanama/">
                    <i class="fa fa-instagram footer-sm text-white" aria-hidden="true"></i>
                </a>
            </div>
        </div>
    </div>
    <div class="container hidden-sm hidden-lg hidden-md">
        <div class="col-xs-12 margin-footer">
            <ul id="footerCol4Row" class="footer-list">
                <li class="text-center" id="">Redes sociales</li>
            </ul>
            <div class="text-center">
                <a href="{% url 'social:begin' 'facebook' %}" type="button" class="btn footer-sm-facebook btn-circle btn-lg" target="_blank">
                    <i class="fa fa-facebook footer-sm text-white" aria-hidden="true"></i>
                </a>
                <a type="button" class="btn footer-sm-youtube btn-circle btn-lg" href="https://www.youtube.com/channel/UCxDrDoFOgKPbgSwq_A4ptAQ">
                    <i class="fa fa-youtube footer-sm text-white" aria-hidden="true"></i>
                </a>
                <a type="button" class="btn footer-sm-facebook btn-circle btn-lg" href="https://www.instagram.com/iurdpanama/">
                    <i class="fa fa-instagram footer-sm text-white" aria-hidden="true"></i>
                </a>
            </div>
        </div>
        <div class="col-xs-12 footer-margin">
            
        </div>
        <div class="col-xs-12 footer-margin">
            
        </div>
    </div>
</div>
<div id="footerRow2" class="row footer-row ident-color-dark">
    <div class="container">
        <div class="col-xs-12 col-sm-4 text-center">
            <p>Copyright {% now "Y" %} Iglesia Oración Fuerte al Espiritu Santo</p>
        </div>
        <div class="col-xs-12 col-sm-4 text-center">
            <p></p>
        </div>
        <div class="col-xs-12 col-sm-4 text-center">
            <p class="dev2tech-logo">Powered by <span class=""><a target="_blank" href="https://dev2tech.xyz">Dev2tech</a></span></p>
        </div>
    </div>
</div>

templates/head.html
{% load staticfiles %}
<link rel="dns-prefetch" href="http://red-aleluya.universal.org.pa">
<link href="https://fonts.googleapis.com/css?family=Lora|Old+Standard+TT|Sarina" rel="stylesheet">
<link  href="{% static 'base/fonts/glyphicons-halflings-regular.eot' %}">
<link rel="stylesheet" href="{% static 'base/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'base/css/app.css' %}">
<link rel="stylesheet" href="{% static 'base/css/colores.css' %}">
<link rel="stylesheet" href="{% static 'base/css/swiper.min.css' %}">
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
<link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
<link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'favicon/manifest.json' %}">
<meta name="msapplication-TileColor" content="#f3f3f3'">
<meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ffffff">
<script src="{% static 'base/js/analytics.js' %}"></script>
<script src="{% static 'base/js/jquery-3.1.1.min.js' %}" charset="utf-8"></script>

templates/header.html
{% load staticfiles %}
<header>
    <div class="hidden-xs row">
        <div class="container-fluid">
            <img src="{% static 'base/images/logo.png' %}" alt="Iglesia oración fuerte al Espiritu Santo" id="logoLarge">
        </div>
    </div>
    <nav id="myMenu" class="navbar navbar-default navbar-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <img src="{% static 'base/images/logo.png' %}" alt="Iglesia oración fuerte al Espiritu Santo" id="logoShort" class="hidden-sm hidden-md hidden-lg">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="{% if pg_title == 'home' %}active{% endif %}">
                        <a href="{% url 'frontend:Home' %}">Inicio</a>
                    </li>
                    <li class="{% if pg_title == 'about' %}active{% endif %}" >
                        <a href="{% url 'frontend:About' %}">¿Quienes somos?</a>
                    </li>
                    <li class="{% if pg_title == 'project' %}active{% endif %}">
                        <a href="{% url 'frontend:Projects' %}">Proyectos</a>
                    </li>
                    <li class="dropdown dropdown-large {% if pg_title == 'reunion' %}active{% endif %}">
                        <a href="{% url 'frontend:Reunions' %}" class="dropdown-toggle" data-toggle="dropdown">
                            Reuniones <b class="caret hidden-xs hidden-sm"></b>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-large row hidden-xs">
                            {% for key, value in weekdays.items|dictsort:0 %}
                                <li class="col-sm-3">
                                    <ul>
                                    {% if forloop.counter == 1 %}
                                        <li class="dropdown-header">Todas las reuniones</li>
                                        <li><a href="{% url 'frontend:Reunions' %}">Ver reuniones</a></li>
                                        <li class="divider"></li>
                                    </ul>
                                </li>
                                <li class="col-sm-3">
                                    <ul>
                                        <li class="dropdown-header">{{value.day}}</li>
                                        {% for key, val in value.reunions.items %}
                                            <li><a href="{{val.url}}">{{val.name}}</a></li>
                                        {% endfor %}
                                        <li class="divider"></li>
                                    {% else %}
                                        <li class="dropdown-header">{{value.day}}</li>
                                        {% for key, val in value.reunions.items %}
                                            <li><a href="{{val.url}}">{{val.name}}</a></li>
                                        {% endfor %}
                                        <li class="divider"></li>
                                    {% endif %}
                                    </ul>
                                    
                                </li>
                            {% endfor %}
                        </ul>
                    </li>
                    <li class="{% if pg_title == 'testimonial' %}active{% endif %}">
                        <a href="{% url 'frontend:Testimonials' %}">Testimonios</a>
                    </li>
                    <li class="{% if pg_title == 'media' %}active{% endif %}">
                        <a href="{% url 'frontend:Media' %}">Multimedia</a>
                    </li>
                    {% if page_aevents %}
                        <li class="{% if pg_title == 'events' %}active{% endif %}">
                            <a href="{% url 'frontend:Events' %}">Eventos</a>
                        </li>
                    {% endif %}
                    <li class="{% if pg_title == 'blog' %}active{% endif %}">
                        <a href="{% url 'frontend:Blog' %}">Blog</a>
                    </li>
                    <li class="{% if pg_title == 'contact' %}active{% endif %}">
                        <a href="{% url 'frontend:Contact' %}">Contacto</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>