local_apps/dashboard/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from local_apps.dashboard import views as dashboard_views

urlpatterns = [
	url(r'^$', dashboard_views.home, name='Home'),
	url(r'^quienes-somos/', dashboard_views.post_church, name='About'),
	url(r'^proyectos/', dashboard_views.projects, name='Projects'),
	url(r'^reuniones/', dashboard_views.reunions, name='Reunions'),
	url(r'^testimonios/', dashboard_views.testimonials, name='Testimonials'),
	url(r'^multimedia/', dashboard_views.media, name='Media'),
	url(r'^noticias/', dashboard_views.blog, name='Blog'),
	url(r'^contacto/', dashboard_views.contact, name='Contact'),
]

settings/urls.py
from django.conf import settings
from django.conf.urls import (include, url, handler400, handler403, handler404, handler500)
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers

from local_apps.profiles.auth import (login,register,logout,activate)
from local_apps.frontend import views as base_views

router = routers.DefaultRouter()
router.register(r'api/users', base_views.UserViewSet)
router.register(r'api/groups', base_views.GroupViewSet)
router.register(r'api/church', base_views.ChurchViewSet)

handler400 = 'local_apps.frontend.views.my_custom_bad_request_view'
handler403 = 'local_apps.frontend.views.my_custom_permission_denied_view'
handler404 = 'local_apps.frontend.views.my_custom_page_not_found_view'
handler500 = 'local_apps.frontend.views.my_custom_error_view'

urlpatterns = [

	url(r'^',include('local_apps.frontend.urls' ,namespace='frontend')),
	url(r'^auth/',include('local_apps.profiles.urls' ,namespace='auth')),
    url(r'^dashboard/',include('local_apps.dashboard.urls' ,namespace='dashboard')),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

    url(r'^', include(router.urls)),
    url(r'^iurd/admin/', admin.site.urls),
    url(r'^api/', include('rest_framework.urls', namespace='rest_framework')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

local_apps/dashboard/models.py
from django.db import models

# Create your models here.

local_apps/dashboard/views.py
from django.contrib import messages
from django.contrib.auth.models import User, Group
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from settings.settings.serializers import UserSerializer, GroupSerializer
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random

from rest_framework import viewsets
from local_apps.iurd.models import *
from local_apps.medias.models import *
from local_apps.news.models import *
from local_apps.testimonials.models import *
from local_apps.iurd.forms import (ChurchForm,EventForm,FeedForm,ProjectForm,ScheduleForm,ReunionForm)


# Create your views here.
@login_required
def home(request):
	template = 'dashboard/index.html'
	context = {
		'pg_title':'',
	}
	return render(request,template,context)

def post_church(request):
	template = 'dashboard/form.html'
	ChurchForm = ChurchForm(request.POST or None, request.FILES or None)

	context = {
		'pg_title':'',
		'form':ChurchForm,
	}
	return render(request,template,context)

def projects(request):
	template = 'dashboard/index.html'
	context = {
		'pg_title':'',
	}
	return render(request,template,context)

def reunions(request):
	template = 'dashboard/index.html'
	context = {
		'pg_title':'',
	}
	return render(request,template,context)

def testimonials(request):
	template = 'dashboard/index.html'
	context = {
		'pg_title':'',
	}
	return render(request,template,context)

def blog(request):
	template = 'dashboard/index.html'
	context = {
		'pg_title':'',
	}
	return render(request,template,context)

def media(request):
	template = 'dashboard/index.html'
	context = {
		'pg_title':'',
	}
	return render(request,template,context)

def contact(request):
	template = 'dashboard/index.html'
	context = {
		'pg_title':'',
	}
	return render(request,template,context)

templates/dashboard/base.html
<!DOCTYPE html>{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dashboard</title>
    {% include 'head.html' %}
    {% block css %} {% endblock %}
</head>
<body>
    <header>
        {% include 'header.html' %}
<!--         <nav id="myMenu" class="navbar navbar-default navbar-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="{% if pg_title == 'home' %}active{% endif %}">
                            <a href="{% url 'dashboard:Home' %}">Inicio</a>
                        </li>
                        <li class="{% if pg_title == 'about' %}active{% endif %}" >
                            <a href="{% url 'dashboard:About' %}">¿Quienes somos?</a>
                        </li>
                        <li class="{% if pg_title == 'project' %}active{% endif %}">
                            <a href="{% url 'dashboard:Projects' %}">Proyectos</a>
                        </li>
                        <li class="dropdown dropdown-large {% if pg_title == 'reunion' %}active{% endif %}">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Reuniones <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-large row">
                                <li class="col-sm-3">
                                    <ul>
                                        <li class="dropdown-header">Ver reuniones</li>
                                        <li>
                                            <a href="{% url 'dashboard:Reunions' %}">Todas las reuniones</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="dropdown-header">
                                            Domingo
                                        </li>
                                        <li>
                                            <a href="#">
                                                Reunión espiritual y familiar
                                            </a>
                                        </li>
                                        <li>
                                            <a href="#">Cura de los vicios</a>
                                        </li>
                                        <li>
                                            <a href="#">Estudio apocalipsis</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="col-sm-3">
                                    <ul>
                                        <li class="dropdown-header">Lunes</li>
                                        <li>
                                            <a href="#">Progreso economico</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="dropdown-header">
                                            Martes
                                        </li>
                                        <li>
                                            <a href="#">Liberación</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="col-sm-3">
                                    <ul>
                                        <li class="dropdown-header">Miércoles</li>
                                        <li>
                                            <a href="#">Noche de salvación</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="dropdown-header">Jueves</li>
                                        <li>
                                            <a href="#">Terapia del amor</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="col-sm-3">
                                    <ul>
                                        <li class="dropdown-header">Viernes</li>
                                        <li>
                                            <a href="#">Liberación espiritual</a>
                                        </li>
                                        <li class="divider"></li>
                                        <li class="dropdown-header">Sabado</li>
                                        <li>
                                            <a href="#">Casos imposibles</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="{% if pg_title == 'testimonial' %}active{% endif %}">
                            <a href="{% url 'dashboard:Testimonials' %}">Testimonios</a>
                        </li>
                        <li class="{% if pg_title == 'blog' %}active{% endif %}">
                            <a href="{% url 'dashboard:Blog' %}">Multimedia</a>
                        </li>
                        <li class="{% if pg_title == 'blog' %}active{% endif %}">
                            <a href="{% url 'dashboard:Blog' %}">Blog</a>
                        </li>
                        <li class="{% if pg_title == 'contact' %}active{% endif %}">
                            <a href="{% url 'dashboard:Contact' %}">Contacto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> -->
    </header>
    <section>{% block content %} {% endblock %}</section>
    <footer>

    </footer>
    {% block js %} {% endblock %}
</body>
</html>

templates/dashboard/form.html
{% extends 'dashboard/base.html' %}
{% load crispy_forms_tags %}

{% block css %}
{% endblock %}

{% block content %}
<div class='col-sm-6'>
	<h1>Preview</h1>
	<hr/>
	<div class='content-preview'>
	    <h3 id='preview-title'></h3>
	    <p id='preview-content'></p>
	</div>
</div>
<div class='col-sm-6'>
	<h1>Form</h1>
	<hr/>

	<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
		{{ form|crispy }}
		<input type='submit' class='btn btn-default' value='Post' />
	</form>
</div>
{% endblock %}

{% block js %}
{% endblock %}


{% block head_extra %} 
{{ form.media }}

{% endblock head_extra %}

templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% block css %}
<style>
	.card-1 {
		box-shadow: 0 1px 3px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);
		transition: all 0.3s cubic-bezier(.25,.8,.25,1);
	}
	.card-1:hover {
		box-shadow: 0 14px 28px rgba(0,0,0,0.25), 0 10px 10px rgba(0,0,0,0.22);
	}
	.card-h2{padding:25px;}
	.card-h2 a{font-family: 'Old Standard TT', serif;}
</style>
{% endblock %}
{% block content %}
<div class="row">
	<div class="container">
		<div class=" col-xs-12 col-sm-4">
			<div class="gray card-1">
				<h2 class="text-center card-h2">
					<a href="">Blog</a>
				</h2>
			</div>
		</div>
		<div class="col-xs-12 col-sm-4">
			<div class="gray card-1">
				<h2 class="text-center card-h2">
					<a href="">Testimonios</a>
				</h2>
			</div>
		</div>
		<div class=" col-xs-12 col-sm-4">
			<div class="gray card-1">
				<h2 class="text-center card-h2">
					<a href="">Multimedia</a>
				</h2>
			</div>
		</div>
		<div class=" col-xs-12 col-sm-4">
			<div class="gray card-1">
				<h2 class="text-center card-h2">
					<a href="">Iglesias</a>
				</h2>
			</div>
		</div>
		<div class=" col-xs-12 col-sm-4">
			<div class="gray card-1">
				<h2 class="text-center card-h2">
					<a href="">Reuniones</a>
				</h2>
			</div>
		</div>
		<div class=" col-xs-12 col-sm-4">
			<div class="gray card-1">
				<h2 class="text-center card-h2">
					<a href="">Proyectos</a>
				</h2>
			</div>
		</div>
		<div class=" col-xs-12 col-sm-4">
			<div class="gray card-1">
				<h2 class="text-center card-h2">
					<a href="">Perfil</a>
				</h2>
			</div>
		</div>
		<div class=" col-xs-12 col-sm-4">
			<div class="gray card-1">
				<h2 class="text-center card-h2">
					<a href="">Boletin de noticias</a>
				</h2>
			</div>
		</div>
		<div class=" col-xs-12 col-sm-4">
			<div class="gray card-1">
				<h2 class="text-center card-h2">
					<a href="">Grupos</a>
				</h2>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block js %}
{% endblock %}